pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'avishkaweera20/devops-frontend'
        DOCKERHUB_CREDENTIALS = 'dockerhub'
    }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/Avishka-Weerasekara/DevOps.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('DevOps/frontend') {
                    sh 'docker build -t $DOCKER_IMAGE:latest .'
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: "$DOCKERHUB_CREDENTIALS", passwordVariable: 'DOCKER_PASS', usernameVariable: 'DOCKER_USER')]) {
                    sh '''
                    echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                    docker push $DOCKER_IMAGE:latest
                    docker logout
                    '''
                }
            }
        }
    }
}
